### ISSUE TITLE
AWS::SES::ResponseError: AWS::SES Response Error: InvalidClientTokenIdThe security token included in the request is invalid

### ISSUE THREAD

**Issue by rezzz-dev** [drewblas/aws-ses#14]
I seem to be getting a strange error when going through the steps to install this.  I went through the initial steps in irb and the new method creates the object just fine, but when I call ses.addresses.list.result, I get AWS::SES::ResponseError: AWS::SES Response Error: InvalidClientTokenIdThe security token included in the request is invalid

Any thoughts/ideas?  I would greatly appreciate it!!!

**Comment by Startouf** [comment]
What was the issue ?
