### ISSUE TITLE
Upgrade to signature v4 necessary

### ISSUE THREAD

**Issue by rickpastoor** [drewblas/aws-ses#71]
Here's the email I got about an impending deprecation:

> Hello,
> 
> Amazon Web Services currently supports Amazon SES API requests that are signed using Signature Version 3 and Signature Version 4 processes. Signature Version 4 further enhances the security around authentication and authorization of Amazon SES customers by using a signing key instead of your secret access key. To improve the security for our customers, beginning October 1, 2020, Amazon Signature Version 3 will be turned off (deprecated) in Amazon SES in favor of Signature Version 4.
> 
> Amazon SES customers who are still using Signature Version 3 must migrate to Signature Version 4 by September 30, 2020. After that, Amazon SES will only accept requests that are signed using Signature Version 4. For more information, see Signature Version 4 signing process [1].

Is anywone working on updating this gem to support V4? Or should I look for a different gem?

**Comment by lvangool** [comment]
I am also wondering about this... in the case of the answer being "NO", are there any other recommended gems for a simple SES Sigv4 use-case? I'm trying to avoid going native with the AWS SDKv3!

**Comment by tirtawr** [comment]
Same here! Still looking for alternative gems

**Comment by teddyswu** [comment]
I am also wondering too. And hope to have an answer! thank

**Comment by coryetzkorn** [comment]
+1 please share if you find an alternative

**Comment by abisosa** [comment]
We just replaced this gem with smtp and aws ses credentials config: https://hixonrails.com/ruby-on-rails-tutorials/ruby-on-rails-action-mailer-configuration/#amazon-ses-account-setup

**Comment by whitmer** [comment]
Anyone tried this https://github.com/tablecheck/mail-ses ? I'm going to play with it but it may take me a couple weeks to get to it..

**Comment by TinNT** [comment]
FYI, This fork https://github.com/ofri-switzerland/aws-ses/pull/1 worked perfectly

**Comment by Pyo25** [comment]
Otherwise there is the official [AWS Rails plugin](https://github.com/aws/aws-sdk-rails ).

**Comment by ncri** [comment]
Can this be closed as https://github.com/ofri-switzerland/aws-ses/pull/1 has been merged?

**Comment by ncri** [comment]
Ah, sorry, my mistake, has only been merged in their fork. I will try that out.

**Comment by drewblas** [comment]
Ideally I'd like to merge in @ofri-switzerland 's fork, however it looks like they hardcoded the us-east-1 REGION into the request.   I believe to really make it work correctly for everyone the us-east-1 could be the _default_ but should also be overridable through a config param

If anyone knows of a fixed version that accomplishes this, I'm happy to merge it and cut a new version!

**Comment by emq** [comment]
Hi @drewblas; fair point! - we probably can make that configurable and prep pull request for review if you're interested in releasing new version of your gem :) /cc @m33h (let's discuss this tomorrow maybe)

**Comment by rickpastoor** [comment]
Just upgraded the gem to the latest version and seems to work perfectly 👍  Thanks @m33h!

**Comment by sunilsoma** [comment]
@lucascaton Do you know how to confirm in rails if ses version is upgraded, how to confirm this in ec2 or rails that now ses version is upgraded? after changing this gem

**Comment by TomohiroKai** [comment]
@sunilsoma In my own way, I checked returned value of mail method like below.
` mail(subject: subject, to: to).to_json`
There is this value. 
`delivery_method>client>config>api>metadata>signatureVersion`
I think If signatureVersion is "v4", then it's fine.

This json is very long. So be careful to handle it (some editor may freeze. I used sublime text and it could handle).
