### ISSUE TITLE
:signature_version not using V4 signing

### ISSUE THREAD

**Issue by jasonblanchard** [drewblas/aws-ses#76]
After doing some testing with [configuration like this](https://github.com/drewblas/aws-ses#for-rails-3x-), this gem does not appear to be using the v4 signing method despite passing in the `:signature_version => 4`

It looks like this might be happening because this line https://github.com/drewblas/aws-ses/blob/532ab658a6f2a662759de148293a8b5276f85153/lib/aws/ses/base.rb#L180 stringifies the `signature_version` which then gets compared to an integer when checking the conditional down here https://github.com/drewblas/aws-ses/blob/532ab658a6f2a662759de148293a8b5276f85153/lib/aws/ses/base.rb#L199. As written, I don't think this will ever take the v4 signing path.

It looks like this might have been introduced right here https://github.com/drewblas/aws-ses/commit/f4ef27d55461531c7c198c7f348f576fc099ae05#diff-b36a5e73febe42aa0b75b3a526a815d1L191 when the "v" got dropped maybe?

**Comment by lvangool** [comment]
Given the deprecation <v4 today, @drewblas would you be able to emergency patch this?
"Amazon Simple Email Service is ending support for Signature Version 3 effective September 30"

**Comment by drewblas** [comment]
Thank you for the quick lead!  I've released the fix - https://rubygems.org/gems/aws-ses/versions/0.7.1
